---
- name: MongoDB Sharding Cluster
  hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: false
  vars:
    - host: "mongodbnode"
    - user: "root"
  roles:
    - common
- hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: false
  vars:
    - host:
      - "mongodbnode-shard1"
    - user: "root"
  roles:
    - role: db_install
      vars:
#        - shardsid: "shard1"
        - repliacsetname: "rs1"
        - dbport: "40010"
#- hosts: "{{host}}"
#  remote_user: "{{user}}"
#  gather_facts: false
#  vars:
#    - host:
#      - "mongodbnode-shard2"
#    - user: "root"
#  roles:
#    - role: db_install
#      vars:
#        - shardsid: "shard2"
#        - repliacsetname: "rs2"
#        - dbport: "40010"
- hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: false
  vars:
    - host:
      - "mongodbnode-config"
    - user: "root"
  roles:
    - role: config_install
      vars:
        - repliacsetname: "configset"
        - configport: "40011"
- hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: false
  vars:
    - host:
      - "mongodbnode-mongos"
    - user: "root"
  roles:
    - role: mongos_install
      vars:
        - mongosport: "40012"
        - repliacsetname: "configset"
        - configport: "40011"
- hosts: 127.0.0.1
  remote_user: root
  gather_facts: false
  roles:
    - keyfile_generate
- hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: false
  vars:
    - host: "mongodbnode"
    - user: "root"
  roles:
    - keyfile_distribution
